### ISSUE TITLE
NameError: name 'expected_output_D' is not defined

### ISSUE THREAD

**Issue by haochenpan** [CihanSoylu/MATH448001#1]
Hi Professor Soylu,

[line 231](https://github.com/CihanSoylu/MATH448001/blob/2f067032c43c1ffb786d24cfec2f220aa44a4728/project_tests/project_1_tests.py#L231) and [line 240](https://github.com/CihanSoylu/MATH448001/blob/2f067032c43c1ffb786d24cfec2f220aa44a4728/project_tests/project_1_tests.py#L240) give me the following error on colab: 

> NameError: name 'expected_output_D' is not defined

I guess the correct variable name is `expected_output_V`?

Best,
Haochen

**Comment by CihanSoylu** [comment]
Hi Haochen,

Thanks for pointing out the issue!

Best,
Cihan
